name: ci
on:
  push:
    branches:
      - main
      - try
  pull_request:

permissions: {}

env:
  flake: github:${{ github.repository }}/${{ github.sha }}
  nix-conf: |-
    accept-flake-config = true
    always-allow-substitutes = true
    builders-use-substitutes = true
    max-jobs = auto
jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v15
        with:
          name: rustc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix-flake-check
        run: nix flake check '${{ env.flake }}'
  flake-show:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v15
        with:
          name: rustc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix-flake-show
        run: nix flake show '${{ env.flake }}'
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v15
        with:
          name: rustc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '${{ env.flake }}#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    needs: [ nix-matrix ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v15
        with:
          name: rustc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: nix-fast-build
        run: |
          declare -a args=(
            '--no-nom'
            '--skip-cached'
            '--systems=${{ env.system }}'
            '--option' 'accept-flake-config' 'true'
            '--retries=3'
          )
          args+=('--flake=${{ env.flake }}#${{ matrix.attr }}')
          nix run '${{ env.flake }}#nix-fast-build' -- "${args[@]}"

  check:
    runs-on: ubuntu-latest
    needs: [ flake-check, flake-show, nix-matrix, nix-build ]
    if: always()
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: eval
